mh_amcl:
  ros__parameters:
    use_sim_time: true

    # Maximum number of hypotheses maintained
    max_hypotheses: 5

    # Enable or disable multi-hypothesis AMCL
    multihypothesis: true

    # Minimum weight for a candidate hypothesis to be considered
    min_candidate_weight: 0.5

    # Minimum distance between candidate hypotheses (in meters)
    min_candidate_distance: 0.5

    # Minimum angular difference between candidate hypotheses (in radians)
    min_candidate_angle: 1.5708 # Equivalent to PI/2

    # Threshold for low-quality hypotheses
    low_q_hypo_threshold: 0.25

    # Threshold for very low-quality hypotheses
    very_low_q_hypo_threshold: 0.1

    # Distance threshold for merging similar hypotheses (in meters)
    hypo_merge_distance: 0.2

    # Angular threshold for merging similar hypotheses (in radians)
    hypo_merge_angle: 0.3

    # Threshold to consider a hypothesis as "good"
    good_hypo_threshold: 0.7

    # Minimum difference in quality between the best hypothesis and others
    min_hypo_diff_winner: 0.2

    # Bond timeout
    bond_timeout: 4.0

    # Standard deviation for the LiDAR
    distance_perception_error: 0.05
