frame_id: map
features:
  - position: [-5, -5, 0.6]
    category: 2
  - position: [-5, -3, 0.6]
    category: 3
  - position: [-5, -2, 0.6]
    category: 0
  - position: [-5, -1, 0.6]
    category: 1
  - position: [-5, 0, 0.6]
    category: 0
  - position: [-5, 1, 0.6]
    category: 1
  - position: [-5, 2, 0.6]
    category: 0
  - position: [-5, 3, 0.6]
    category: 3
  - position: [-5, 5, 0.6]
    category: 2
  - position: [-3, -5, 0.6]
    category: 3
  - position: [-3, 5, 0.6]
    category: 3
  - position: [-2, -5, 0.6]
    category: 0
  - position: [-2, 5, 0.6]
    category: 0
  - position: [-1, -5, 0.6]
    category: 1
  - position: [-1, 5, 0.6]
    category: 1
  - position: [0, -5, 0.6]
    category: 0
  - position: [0, 5, 0.6]
    category: 0
  - position: [1, -5, 0.6]
    category: 1
  - position: [1, 5, 0.6]
    category: 1
  - position: [2, -5, 0.6]
    category: 0
  - position: [2, 5, 0.6]
    category: 0
  - position: [3, -5, 0.6]
    category: 3
  - position: [3, 5, 0.6]
    category: 3
  - position: [5, -5, 0.6]
    category: 2
  - position: [5, -3, 0.6]
    category: 3
  - position: [5, -2, 0.6]
    category: 0
  - position: [5, -1, 0.6]
    category: 1
  - position: [5, 0, 0.6]
    category: 0
  - position: [5, 1, 0.6]
    category: 1
  - position: [5, 2, 0.6]
    category: 0
  - position: [5, 3, 0.6]
    category: 3
  - position: [5, 5, 0.6]
    category: 2
