frame_id: map
features:
  - position: [-1.2, 2.1, 5]
    category: 0
  - position: [-3, 2.1, 5]
    category: 0
  - position: [-4.8, 2.1, 5]
    category: 0
  - position: [-6.6, 2.1, 5]
    category: 0
  - position: [-8.4, 2.1, 5]
    category: 0
  # - position: [-1.2, 4.5, 5]
  #   category: 0
  - position: [-3, 4.5, 5]
    category: 0
  # - position: [-4.8, 4.5, 5]
  #   category: 0
  - position: [-6.6, 4.5, 5]
    category: 0
  - position: [-8.4, 4.5, 5]
    category: 0
  - position: [-1.2, 6.9, 5]
    category: 0
  - position: [-3, 6.9, 5]
    category: 0
  - position: [-4.8, 6.9, 5]
    category: 0
  - position: [-6.6, 6.9, 5]
    category: 0
  - position: [-8.4, 6.9, 5]
    category: 0
  - position: [-1.2, 9.6, 5]
    category: 0
  # - position: [-3, 9.6, 5]
  #   category: 0
  - position: [-4.8, 9.6, 5]
    category: 0
  - position: [-6.6, 9.6, 5]
    category: 0
  - position: [-8.4, 9.6, 5]
    category: 0
  - position: [-1.2, 12, 5]
    category: 0
  - position: [-3, 12, 5]
    category: 0
  # - position: [-4.8, 12, 5]
  #   category: 0
  - position: [-6.6, 12, 5]
    category: 0
  - position: [-8.4, 12, 5]
    category: 0
