frame_id: map
features:
  - position: [-6 , -6 , 1.0]
    category: 0
  - position: [-6 , -2, 1.0]
    category: 0
  - position: [-6 , 0, 1.0]
    category: 0
  - position: [-6 , 2, 1.0]
    category: 0
  - position: [-6 , 6 , 1.0]
    category: 0
  - position: [-2, -6 , 1.0]
    category: 0
  - position: [-2, 6 , 1.0]
    category: 0
  - position: [0, -6 , 1.0]
    category: 0
  - position: [0, 6 , 1.0]
    category: 0
  - position: [2, -6 , 1.0]
    category: 0
  - position: [2, 6 , 1.0]
    category: 0
  - position: [6 , -6 , 1.0]
    category: 0
  - position: [6 , -2, 1.0]
    category: 0
  - position: [6 , 0, 1.0]
    category: 0
  - position: [6 , 2, 1.0]
    category: 0
  - position: [6 , 6 , 1.0]
    category: 0
