/**:
  controller_manager:
    ros__parameters:
      use_sim_time: true
      update_rate: 50

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      mecanum_drive_controller:
        type: mecanum_drive_controller/MecanumDriveController

  mecanum_drive_controller:
    ros__parameters:
      front_left_wheel_command_joint_name: "front_left_wheel_joint"
      rear_left_wheel_command_joint_name: "back_left_wheel_joint"
      front_right_wheel_command_joint_name: "front_right_wheel_joint"
      rear_right_wheel_command_joint_name: "back_right_wheel_joint"

      # Kinematic parameters from the URDF
      wheel_separation_x: 0.43056 # distance between front and back wheels
      wheel_separation_y: 0.518   # distance between left and right wheels
      wheel_radius: 0.127         # radius of wheels

      # Optional but useful:
      #cmd_vel_timeout:   0.25
      #use_stamped_vel:   false
      #publish_rate:      50
      enable_odom_tf:    true
      odom_frame_id: "odom"
      base_frame_id: "base_footprint"
      twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
      pose_covariance_diagonal: [0.0, 6.0, 12.0, 18.0, 24.0, 30.0]